spring:
  application:
    name: calculator
  datasource:
    url: jdbc:h2:mem:calculatordb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: calculatorSecretKey123456789012345678901234567890
  expiration: 86400000
