server:
  port: 8080
spring:
  application:
    name: calculator
  datasource:
    url: jdbc:mysql://localhost:3306/ravendb
    username: user
    password: UserPass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#Se define un secret con el cual se genere el JWT y se define un tiempo de expiración
jwt:
  secret: calculatorSecretKey123456789012345678901234567890
  expiration: 86400000

mailboxlayer:
  key: 58328a60192649ce33cfcb4d06436b74
  url-api: http://apilayer.net/api/check

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.mx.raven.calculator.controllers
